name: Deploy Flask App

on:
  push:
    branches: [ master ]  # Change this to your main branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask gunicorn
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: 85.198.17.236
        username: root
        password: 133976beh
        script: |
          # Create directory if it doesn't exist
          mkdir -p /var/www/flask-app
          
          # Create virtual environment if it doesn't exist
          if [ ! -d "/var/www/flask-app/venv" ]; then
            python3 -m venv /var/www/flask-app/venv
          fi
          
          # Activate virtual environment and install dependencies
          source /var/www/flask-app/venv/bin/activate
          pip install flask gunicorn
          
          # Create a temporary file for comparing if requirements.txt exists
          echo "flask\ngunicorn" > /tmp/default_requirements.txt
          if [ ! -f "/var/www/flask-app/requirements.txt" ]; then
            cp /tmp/default_requirements.txt /var/www/flask-app/requirements.txt
          fi
          
          pip install -r /var/www/flask-app/requirements.txt
          
          # Create or update systemd service
          cat > /tmp/flask-app.service << 'EOL'
          [Unit]
          Description=Flask App Service
          After=network.target
          
          [Service]
          User=root
          WorkingDirectory=/var/www/flask-app
          ExecStart=/var/www/flask-app/venv/bin/gunicorn app:app -b 127.0.0.1:8000
          Restart=always
          
          [Install]
          WantedBy=multi-user.target
          EOL
          
          mv /tmp/flask-app.service /etc/systemd/system/flask-app.service
          systemctl daemon-reload
          
          # Configure Nginx
          cat > /tmp/flask-app << 'EOL'
          server {
              listen 80;
              server_name 82.115.21.17;
              
              location / {
                  proxy_pass http://127.0.0.1:8000;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
              }
          }
          EOL
          
          mv /tmp/flask-app /etc/nginx/sites-available/flask-app
          ln -sf /etc/nginx/sites-available/flask-app /etc/nginx/sites-enabled/
          nginx -t && systemctl restart nginx

    - name: Copy application files
      uses: appleboy/scp-action@master
      with:
        host: 85.198.17.236
        username: root
        password: 133976beh
        source: "*.py,templates/*,static/*,*.json"
        target: "/var/www/flask-app"
        strip_components: 0

    - name: Restart application
      uses: appleboy/ssh-action@master
      with:
        host: 85.198.17.236
        username: root
        password: 133976beh
        script: |
          systemctl restart flask-app
          echo "Deployment completed successfully!"
